name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - uses: dschep/install-pipenv-action@v1
    - name: Run Tests
      run: |
        pipenv install --dev
        PYTHONPATH=.. pipenv run green -vvv --run-coverage
    - name: Test with tox
      run: pipenv run tox
